### ISSUE TITLE
Unhandled non-manifold paths (aka Stuck at pre-load)

### ISSUE THREAD

**Issue by TheOfficialCzex** [9swampy/DeepNestSharp#8] opened 2022-01-20 10:22 UTC
I'm sure I'm just doing something incorrectly, but I can't seem to pass pre-loading after execute. Stopping the application at this point causes a hard crash, too.

**Comment by 9swampy** [comment] 2022-01-23 19:54
Whether you're doing right or wrong there should be some logs to help explain. Anything you could share? Even what you're trying to execute maybe?

**Comment by TheOfficialCzex** [comment] 2022-01-24 05:22
Load new project
Add parts and adjust quantities as necessary
Add sheet of given size and quantity
Execute

At this point, the application is stuck on Preloading the first DXF. Clicking "Stop" crashes the application to desktop.

**Comment by 9swampy** [comment] 2022-02-06 02:41
Works for me; I'd guess it'll be something wrong with your dxfs. Try using the sample dxfs in https://github.com/9swampy/DeepNestSharp/tree/master/DeepNestPort/dxfs and if you can replicate the error with those update the steps to reproduce; I'll try again.

**Comment by TheOfficialCzex** [comment] 2022-02-06 02:44
Must be my DXFs. I exported straight from Fusion 360, but DeepNest (non-Sharp) refused to treat them.

[Spider Lamp V2.zip](https://github.com/9swampy/DeepNestSharp/files/8009301/Spider.Lamp.V2.zip)

**Comment by 9swampy** [comment] 2022-02-06 02:59
Yeah, it's your dxfs - but it should at least let you know gracefully not die as you've reported. I'll have a look in to what's going wrong there... but it won't fix your issue unless you can correct the dxfs.

Start application
File -> New Project
Add Parts - multiselect all the files in your (extracted) zip.

![image](https://user-images.githubusercontent.com/523054/152666052-d684db1a-b938-41e6-bbf2-5857b0041e9f.png)

I also opened one of the dxfs from the path noted above; the last on the list; selected.

In the preview you'll see an outline, green where there's material and the pink for any holes to be cut. The example's a beer bottle opener; as you see above.

If I select each of your dxfs none have a preview; they're invalid files - except for the last two; which are clearly confused too:
![image](https://user-images.githubusercontent.com/523054/152666103-2b362929-da9d-40ae-9e1c-7217f2ca5a14.png)

![image](https://user-images.githubusercontent.com/523054/152666107-5ffcb7a4-7ab8-423f-bc3f-cf91685e1551.png)

See if you can regenerate the dxfs. FWIW I use OpenScad which works a treat; ofc YMMV.

**Comment by 9swampy** [comment] 2022-02-06 03:06
MAy help you fix the dxfs; System.ArgumentException: unsupported entity type: IxMilia.Dxf.Entities.DxfInsert

**Comment by hutje** [comment] 2022-03-17 15:33
I got the same problem here... It is stuck at pre-load when using a dxf-file.

**Comment by TheOfficialCzex** [comment] 2022-03-17 15:35
> I got the same problem here...

I narrowed it down to disconnected paths that were supposed to be connected. Usually results from compound paths not being explicitly defined as the same path.

**Comment by hutje** [comment] 2022-03-17 15:38
> I narrowed it down to disconnected
This is not the actual fix right? Just a quick fix? Because currently none of the downloaded dxf-files do work.

**Comment by TheOfficialCzex** [comment] 2022-03-17 15:42
If your paths aren't closed, it can't nest. There's no built-in tolerance for paths to join. If they're not explicitly defined as compound paths in the DXF file, it will assume they're independent and fail to nest. Attempt to fix your DXFs by joining paths in a vector editor, like Inkscape or Illustrator.

**Comment by hutje** [comment] 2022-03-17 15:45
> If your paths aren't closed

The paths should be closed, otherwise I can't lasercut the parts.

**Comment by hutje** [comment] 2022-03-17 15:47
This file is an example of files I can't get to work in the software.
[](https://speypers.com/download/bee-3mm-insect-3d-wood-puzzle-free-dxf-file/)

**Comment by TheOfficialCzex** [comment] 2022-03-17 15:48
Right, but the nesting application treats implicitly joined paths as separate. They need to be defined as compound paths for it to recognize a manifold shape and nest.

**Comment by TheOfficialCzex** [comment] 2022-03-17 15:50
The reason why they're still laser-cut-able is because their endpoints are coincident with other endpoints or are so close that the kerf of the laser beam is adequate to "cross the gap."

**Comment by 9swampy** [comment] 2022-03-17 23:02
Thanks @TheOfficialCzex all as you've said. The link you posted hutje didn't easily bring me to cut-able individual layers but each layer will need to be valid in it's own right as @TheOfficialCzex noted.

@TheOfficialCzex were you successful in resolving your original issues by fixing the dxfs?

**Comment by TheOfficialCzex** [comment] 2022-03-17 23:07
Yes. Compounding paths that coincided at their endpoints but weren't yet explicitly compound fixed my issue. Seems that the application assumes the path should be closed by connecting the endpoints of the non-manifold paths with straight lines. Perhaps, a good solution would be some tolerance for connecting the endpoints of separate paths.

**Comment by 9swampy** [comment] 2022-03-17 23:16
Excellent; glad @TheOfficialCzex you sorted your issue. Happy to keep the ticket open as the issue is as much that it bombs instead of gracefully explaining why.

...but if we see further it's because your proposal makes perfect sense and I know the DXF parser is limited as inherited; but it works if you've got conforming DXFs. Happy to PR tolerant distinct endpoints. That should be extensive not a change?

**Comment by 9swampy** [comment] 2022-06-15 01:08
I've put logic in to detect invalid files and prevent execution until they're removed (or fixed). Isn't perfect as some files aren't detected as invalid but the preview should make it pretty obvious they're invalid even if they're not preventing the execution. Hope this helps. I'll publish a beta artefact for review...

![image](https://user-images.githubusercontent.com/523054/173714464-098bca04-e966-403e-8dca-347d6628b5c5.png)

**Comment by 9swampy** [comment] 2022-06-15 01:25
https://github.com/9swampy/DeepNestSharp/releases/tag/v0.2.0-UsabilityEnhancements

**Closed** 2022-06-19 10:59 UTC
